name: hotel_booking
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  simple_animations: ^1.3.3
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  cached_network_image: ^3.1.0
  badges: ^2.0.2
  carousel_slider: ^4.0.0
  image_stack: ^2.1.1
  get: ^4.6.1
  
  
  
  #firebase dependencies
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  cloud_firestore_web: ^2.6.10
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
    image_path: "assets/icon/icon1.png"
    android: true
    ios: true
    
    
flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/